modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="aeprimitives_powah"
version="${version}"
displayName="AE Primitives: Powah"
description="AE-managed Powah processing machines."
[[dependencies.aeprimitives_powah]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.aeprimitives_powah]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.aeprimitives_powah]]
modId="ae2"
type="required"
versionRange="[19.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.aeprimitives_powah]]
modId="aeprimitives"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.aeprimitives_powah]]
modId="powah"
type="required"
versionRange="[6.2,)"
ordering="AFTER"
side="BOTH"
