modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="aeprimitives_kinetics"
version="${version}"
displayName="AE Primitives: Kinetics"
authors="Yuzhe"
description='Create kinetic processing for AE Primitives.'
[[dependencies.aeprimitives_kinetics]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.aeprimitives_kinetics]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.aeprimitives_kinetics]]
modId="ae2"
type="required"
versionRange="[19.2,20.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.aeprimitives_kinetics]]
modId="aeprimitives"
type="required"
versionRange="[0,1.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.aeprimitives_kinetics]]
modId="create"
type="required"
versionRange="[6.0.10,6.1)"
ordering="AFTER"
side="BOTH"
[[dependencies.aeprimitives_kinetics]]
modId="jei"
type="optional"
versionRange="[19.39,20.0)"
ordering="AFTER"
side="CLIENT"
