modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="aeprimitives_farmersdelight"
version="${version}"
displayName="AE Primitives: Farmer's Delight"
authors="Yuzhe"
description="Farmer's Delight processing for AE Primitives."

[[dependencies.aeprimitives_farmersdelight]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeprimitives_farmersdelight]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.aeprimitives_farmersdelight]]
modId="ae2"
type="required"
versionRange="[19.2,20.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.aeprimitives_farmersdelight]]
modId="aeprimitives"
type="required"
versionRange="[0,1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.aeprimitives_farmersdelight]]
modId="farmersdelight"
type="required"
versionRange="[1.2.8,1.3)"
ordering="AFTER"
side="BOTH"
